### ISSUE TITLE
NameError: name 'SupportedOS' is not defined

### ISSUE THREAD

**Issue by m1-ops** [HavocFramework/havoc-py#1]
Hi, I am trying to run the 'havoc_agent.py' script and I am having some difficulties. This is the error I get whilst trying to run:

Traceback (most recent call last):
  File "c:\Users\admin\Desktop\havoc-py-main\havoc-py-main\havoc_agent.py", line 89, in <module>
    class Azazel(AgentType):
  File "c:\Users\admin\Desktop\havoc-py-main\havoc-py-main\havoc_agent.py", line 143, in Azazel
    SupportedOS.Windows
NameError: name 'SupportedOS' is not defined

Any help would be appreciated!

**Comment by Cracked5pider** [comment]
This option has been removed.
